#This will find the instance with the listed Name tag.  Then assign the info for that instance to ec2_facts. 
#That info will be usd as the instnace_id of the task to delete the instance
- hosts: localhost
  gather_facts: yes
  vars_files:
       - keys.yml
       - hostname.yml
  tasks:
          - name: Get the instance ID by tag
            ec2_instance_facts:
                  aws_access_key: "{{AWS_ACCESS_KEY}}"
                  aws_secret_key: "{{AWS_SECRET_KEY}}"
                  ec2_region: "{{ AWS_REGION }}"
                  filters:
                          tag:Name: "{{HOST_NAME}}"
            register: ec2_facts
          - debug:
                  var: ec2_facts.instances[0].instance_id  
          - name: terminate the instnace selected above
            ec2:
                  aws_access_key: "{{AWS_ACCESS_KEY}}"
                  aws_secret_key: "{{AWS_SECRET_KEY}}"
                  ec2_region: "{{ AWS_REGION }}"
                  instance_ids:  
                   - "{{ ec2_facts.instances[0].instance_id}}"
                  state: absent
            register: ec2
          - debug:
                  var: ec2
